{{- $cluster_name := default "mycluster" .Release.Name }}
{{- if not .Values.credentials.root.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cluster_name }}-cluster-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  rootUser: {{ .Values.credentials.root.user | default "root" | quote }}
  rootHost: {{ .Values.credentials.root.host | default "%%" | quote }}
  rootPassword: {{ required "credentials.root.password is required when credentials.root.existingSecret is not set" .Values.credentials.root.password | quote }}
{{- end }}
