#!/bin/bash
# Copyright (c) 2021, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
#

export TESTPOD_NAME=testpod

NAMESPACE=mysql-operator

export PYTHONPATH=`dirname $PWD`

python3 ./run_e2e_tests.py run "$@"
echo "Tests finished. rc=$?"
