#!/bin/bash
# Copyright (c) 2021, Oracle and/or its affiliates.

export TESTPOD_NAME=testpod

NAMESPACE=mysql-operator

if [ -z "$MYSQLSH_BASEDIR" ]; then
    MYSQLSH_BASEDIR=../bld/
fi

if [ ! -f "$MYSQLSH_BASEDIR/bin/mysqlsh" ]; then
    echo "Please set MYSQLSH_BASEDIR to the mysqlsh installation basedir"
    exit 1
fi
echo "Using mysqlsh installation at $MYSQLSH_BASEDIR"

export PYTHONPATH=`dirname $PWD`

"$MYSQLSH_BASEDIR/bin/mysqlsh" -f ./run_e2e_tests.py run $*
echo "Tests finished. rc=$?"

