apiVersion: v2
appVersion: "26.7.0-2.3.0"
name: mysql-operator
description: MySQL Operator Helm Enterprise Chart for deploying MySQL InnoDB Cluster in Kubernetes
type: application
version: "2.3.0"
icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png
