# Copyright (c) 2022, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
#

ARG BASE_IMAGE
FROM $BASE_IMAGE

COPY mysqloperator/ /usr/lib/mysqlsh/python-packages/mysqloperator
