{{- with (include "mysql-operator.disableLookupsWarning" . | trim) -}}
# {{ . | replace "\n" "\n# " }}
{{- end -}}
{{- with (include "mysql-operator.deprecationWarnings" . | trim) -}}
# {{ . | replace "\n" "\n# " }}
{{- end -}}
