{{- include "mysql-operator.checkNotDefaultNamespace" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-operator.deploymentName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 9443
    protocol: TCP
  selector:
    {{- include "mysql-operator.serviceSelectorLabels" . | nindent 4 }}
