// Copyright (c) 2022,2023, Oracle and/or its affiliates.
//
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
//

// handle to util functions module
def utils;

pipeline {
	agent {
		node {
			label 'operator-ci'
		}
	}
	parameters {
		string(name: 'OPERATOR_GIT_REPO_URL', defaultValue: "${env.MYREPO_GIT_REPO_URL}", description: 'a git repository url', trim: true)
		string(name: 'OPERATOR_GIT_REPO_NAME', defaultValue: 'origin', description: 'a git repository name, e.g. origin, gerrit', trim: true)
		string(name: 'OPERATOR_GIT_REVISION', description: 'a git revision or branch to run against', trim: true)
		string(name: 'OPERATOR_GIT_REFSPEC', defaultValue: "${params.OPERATOR_GIT_REVISION}", description: 'a git refspec - commit id or gerrit patchset', trim: true)
		string(name: 'OPERATOR_GIT_BRANCH', description: 'a readable git branch name', trim: true)
		string(name: 'OPERATOR_IMAGE', description: 'an image related to the aforementioned git revision', trim: true)
		string(name: 'OPERATOR_ENTERPRISE_IMAGE', description: '...and a related enterprise image, it can be empty, then it will be built locally', trim: true)
		string(name: 'OPERATOR_TRIGGERED_BY', defaultValue: 'concourse', description: 'how the build was triggered - the following flows are supported: concourse, internal, or gerrit', trim: true)
		booleanParam(name: 'OPERATOR_BUILD_IMAGES', defaultValue: false, description: 'indicates whether the images should be built locally by us (e.g. in case of a push to a dev branch) or use ones delivered externally (e.g. from the concourse)')
		booleanParam(name: 'OPERATOR_ALLOW_WEEKLY_IMAGES', defaultValue: true, description: 'allows to use the not-so-stable router and server weekly images')
		string(name: 'OPERATOR_GERRIT_CHANGE_URL', description: 'link to gerrit Code Review', trim: true)
		string(name: 'OPERATOR_GERRIT_TOPIC', description: 'name of a dev branch used for gerrit CR', trim: true)
		string(name: 'OPERATOR_GERRIT_CHANGE_NUMBER', description: 'gerrit CR change number', trim: true)
		string(name: 'OPERATOR_GERRIT_PATCHSET_NUMBER', description: 'gerrit CR patchset number', trim: true)
		string(name: 'OPERATOR_GERRIT_CHANGE_ID', description: 'gerrit CR Change-ID', trim: true)
	}
 	options {
		timeout(time: 24, unit: 'HOURS')
		timestamps()
	}
	stages {
		stage('init') {
			steps {
				script {
					utils = load "${WORKSPACE}/tests/ci/pipeline/utils.groovy"
					utils.initEnv()

					slackSend channel: "${env.SLACK_CHANNEL}",
						color: utils.getIntroColor(),
						attachments: utils.getIntroContents()

					sh 'mkdir -p ${LOG_DIR}'

					build job: "${env.WORKERS_FOLDER}/init", parameters: [
						string(name: 'OPERATOR_GIT_REPO_URL', value: params.OPERATOR_GIT_REPO_URL),
						string(name: 'OPERATOR_GIT_REPO_NAME', value: params.OPERATOR_GIT_REPO_NAME),
						string(name: 'OPERATOR_GIT_REVISION', value: params.OPERATOR_GIT_REVISION),
						string(name: 'OPERATOR_GIT_REFSPEC', value: params.OPERATOR_GIT_REFSPEC),
						string(name: 'OPERATOR_IMAGE', value: params.OPERATOR_IMAGE),
						string(name: 'OPERATOR_ENTERPRISE_IMAGE', value: params.OPERATOR_ENTERPRISE_IMAGE),
						string(name: 'OPERATOR_TRIGGERED_BY', value: params.OPERATOR_TRIGGERED_BY),
						booleanParam(name: 'OPERATOR_BUILD_IMAGES', value: params.OPERATOR_BUILD_IMAGES),
						booleanParam(name: 'OPERATOR_ALLOW_WEEKLY_IMAGES', value: params.OPERATOR_ALLOW_WEEKLY_IMAGES)
					]
					env.INIT_STAGE_SUCCEEDED = true
				}
			}
		}
		stage('build') {
			when {
				expression { params.OPERATOR_BUILD_IMAGES }
			}
			steps {
				script {
					build job: "${env.WORKERS_FOLDER}/build", parameters: [
						string(name: 'OPERATOR_GIT_REPO_URL', value: params.OPERATOR_GIT_REPO_URL),
						string(name: 'OPERATOR_GIT_REPO_NAME', value: params.OPERATOR_GIT_REPO_NAME),
						string(name: 'OPERATOR_GIT_REVISION', value: params.OPERATOR_GIT_REVISION),
						string(name: 'OPERATOR_GIT_REFSPEC', value: params.OPERATOR_GIT_REFSPEC),
						string(name: 'OPERATOR_IMAGE', value: env.OPERATOR_COMMUNITY_IMAGE),
						string(name: 'OPERATOR_ENTERPRISE_IMAGE', value: params.OPERATOR_ENTERPRISE_IMAGE),
						string(name: 'OPERATOR_TRIGGERED_BY', value: params.OPERATOR_TRIGGERED_BY),
						booleanParam(name: 'OPERATOR_BUILD_IMAGES', value: params.OPERATOR_BUILD_IMAGES)
					]
					env.BUILD_STAGE_SUCCEEDED = true
				}
			}
		}
		stage('test') {
			parallel {
				stage('minikube') {
					steps {
						echo "minikube"
						catchError {
							build job: "${env.WORKERS_FOLDER}/minikube", parameters: [
								string(name: 'OPERATOR_GIT_REPO_URL', value: params.OPERATOR_GIT_REPO_URL),
								string(name: 'OPERATOR_GIT_REPO_NAME', value: params.OPERATOR_GIT_REPO_NAME),
								string(name: 'OPERATOR_GIT_REVISION', value: params.OPERATOR_GIT_REVISION),
								string(name: 'OPERATOR_GIT_REFSPEC', value: params.OPERATOR_GIT_REFSPEC),
								string(name: 'OPERATOR_IMAGE', value: env.OPERATOR_COMMUNITY_IMAGE),
								string(name: 'OPERATOR_ENTERPRISE_IMAGE', value: params.OPERATOR_ENTERPRISE_IMAGE),
								string(name: 'OPERATOR_WORKERS_COUNT', value: '3'),
								string(name: 'OPERATOR_NODE_MEMORY', value: '8192'),
								string(name: 'OPERATOR_TRIGGERED_BY', value: params.OPERATOR_TRIGGERED_BY)
							]
						}
					}
					post {
						always {
							echo "copy minikube results"
							catchError {
								copyArtifacts fingerprintArtifacts: true,
									projectName: "${env.WORKERS_FOLDER}/minikube",
									selector: lastCompleted(),
									target: "${LOG_SUBDIR}"
							}
						}
						cleanup {
							script {
								env.MINIKUBE_RESULT_STATUS = utils.addTestResults("minikube", 1)
							}
						}
					}
				}
				stage('k3d') {
					// with agent set, some files will be stored in $WORKSPACE_TMP
					// agent {
					// 	label "operator-ci"
					// }
					steps {
						echo "k3d"

						// run k3d clusters with some delay (in seconds), after all minikube clusters already
						// have started when clusters start at the same moment, they may fail randomly
						sleep 300
						catchError {
							build job: "${env.WORKERS_FOLDER}/k3d", parameters: [
								string(name: 'OPERATOR_GIT_REPO_URL', value: params.OPERATOR_GIT_REPO_URL),
								string(name: 'OPERATOR_GIT_REPO_NAME', value: params.OPERATOR_GIT_REPO_NAME),
								string(name: 'OPERATOR_GIT_REVISION', value: params.OPERATOR_GIT_REVISION),
								string(name: 'OPERATOR_GIT_REFSPEC', value: params.OPERATOR_GIT_REFSPEC),
								string(name: 'OPERATOR_IMAGE', value: env.OPERATOR_COMMUNITY_IMAGE),
								string(name: 'OPERATOR_ENTERPRISE_IMAGE', value: params.OPERATOR_ENTERPRISE_IMAGE),
								string(name: 'OPERATOR_WORKERS_COUNT', value: '4'),
								string(name: 'OPERATOR_NODE_MEMORY', value: '8192'),
								string(name: 'OPERATOR_TRIGGERED_BY', value: params.OPERATOR_TRIGGERED_BY)
							]
						}
					}
					post {
						always {
							echo "copy k3d results"
							catchError {
								copyArtifacts fingerprintArtifacts: true,
									projectName: "${env.WORKERS_FOLDER}/k3d",
									selector: lastCompleted(),
									target: "${LOG_SUBDIR}"
							}
						}
						cleanup {
							script {
								env.K3D_RESULT_STATUS = utils.addTestResults("k3d", 1)
							}
						}
					}
				}
			}
			post {
				always {
					script {
						if (utils.anyResultsAvailable()) {
							build job: "${env.WORKERS_FOLDER}/prepare-test-suite-report", parameters: [
								string(name: 'OPERATOR_GIT_REPO_URL', value: params.OPERATOR_GIT_REPO_URL),
								string(name: 'OPERATOR_GIT_REPO_NAME', value: params.OPERATOR_GIT_REPO_NAME),
								string(name: 'OPERATOR_GIT_REVISION', value: params.OPERATOR_GIT_REVISION),
								string(name: 'OPERATOR_GIT_REFSPEC', value: params.OPERATOR_GIT_REFSPEC),
								string(name: 'TEST_RESULT_BUILD_URL', value: env.BUILD_URL)
							]

							copyArtifacts fingerprintArtifacts: true,
								projectName: "${env.WORKERS_FOLDER}/prepare-test-suite-report",
								selector: lastCompleted(),
								target: "${LOG_SUBDIR}"

							env.TEST_SUITE_REPORT = utils.getTestSuiteReport()
						} else {
							env.TEST_SUITE_REPORT = ""
						}
					}
				}
				cleanup {
					script {
						env.TESTS_SUITE_ISSUES = utils.getTestsSuiteIssues(false)
					}
				}
			}
		}
	}
	post {
		always {
			script {
				env.BUILD_DURATION = utils.getBuildDuration()
				env.CHANGE_LOG = utils.getChangeLog()

				sh 'ls -lRF ${LOG_DIR}'
				if (utils.anyResultsAvailable()) {
					sh "cd ${LOG_DIR} && tar cvjf ${ARTIFACT_PATH} *"
					archiveArtifacts artifacts: "${ARTIFACT_FILENAME}", fingerprint: true
				}
			}
		}
		changed {
			script {
				utils.modifyBuildStatus("changed")
			}
		}
		fixed {
			script {
				utils.modifyBuildStatus("fixed")
			}
		}
		unstable {
			script {
				utils.modifyBuildStatus("unstable")
			}
		}
		regression {
			script {
				utils.modifyBuildStatus("regression")
			}
		}
		failure {
			script {
				utils.modifyBuildStatus("failure")
			}
		}
		aborted {
			script {
				utils.modifyBuildStatus("aborted")
			}
		}
		unsuccessful {
			script {
				utils.modifyBuildStatus("unsuccessful")
			}
		}
		success {
			script {
				utils.modifyBuildStatus("success")
			}
		}
		cleanup {
			script {
				slackSend channel: "${env.SLACK_CHANNEL}",
					color: utils.getBuildResultColor(),
					attachments: utils.getBuildSummary()
			}
		}
	}
}
