#!/bin/bash
# Copyright (c) 2022, 2023 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
#
# a helper job to trigger the weekly build
set -vx

source $WORKSPACE/tests/ci/jobs/auxiliary/set-env.sh || return

PIPELINE_NAME=weekly

case "${JOB_PREFIX}" in
*/sandbox/*)
  OPERATOR_GIT_REVISION=${GIT_BRANCH}
  ;;
*)
  OPERATOR_GIT_REVISION=trunk
  ;;
esac

OPERATOR_IMAGE=$LOCAL_REGISTRY_ADDRESS/$LOCAL_REPOSITORY_NAME/$COMMUNITY_OPERATOR_IMAGE_NAME:$OPERATOR_BASE_VERSION_TAG
OPERATOR_ENTERPRISE_IMAGE=$LOCAL_REGISTRY_ADDRESS/$LOCAL_REPOSITORY_NAME/$ENTERPRISE_OPERATOR_IMAGE_NAME:$OPERATOR_BASE_VERSION_TAG
OPERATOR_INTERNAL_BUILD='false'

case "$(date +%A)" in
Sunday)
  # temporary policy: allow weekly images on the Sunday's weekly build
  OPERATOR_ALLOW_WEEKLY_IMAGES='true'
  ;;
*)
  OPERATOR_ALLOW_WEEKLY_IMAGES='false'
  ;;
esac

JOB_PARAMS="OPERATOR_GIT_REVISION=${OPERATOR_GIT_REVISION}&OPERATOR_IMAGE=${OPERATOR_IMAGE}"
JOB_PARAMS="${JOB_PARAMS}&OPERATOR_ENTERPRISE_IMAGE=${OPERATOR_ENTERPRISE_IMAGE}&OPERATOR_INTERNAL_BUILD=${OPERATOR_INTERNAL_BUILD}"
JOB_PARAMS="${JOB_PARAMS}&OPERATOR_ALLOW_WEEKLY_IMAGES=${OPERATOR_ALLOW_WEEKLY_IMAGES}"

JOB_LINK=${JOB_PREFIX}/${PIPELINE_NAME}
curl -X POST -u ${JENKINS_USER_CRED} ${JOB_LINK}/buildWithParameters?${JOB_PARAMS}
