{{- include "mysql-operator.checkNotDefaultNamespace" . -}}
# Give access to the operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mysql-operator.operatorRoleBindingName" . }}
  labels:
    {{- include "mysql-operator.globalLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mysql-operator.operatorSAName" . }}
    namespace: {{ .Release.Namespace }}
  # TODO The following entry is for dev purposes only
  #- kind: Group
  #  name: system:serviceaccounts
  #  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ include "mysql-operator.operatorRoleName" . }}
  apiGroup: rbac.authorization.k8s.io